### ISSUE TITLE
Errors on 2 indexes tnt space

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool-perl#9]
Errors while connecting to tnt with 2 indexes in one space:
```
[perl_emerg] unknown field type: undef at 
/usr/lib64/perl5/vendor_perl/DR/Tarantool/MsgPack/LLClient.pm line 196

[perl_warn] EV: error in callback (ignoring): unknown field type: undef at
/usr/lib64/perl5/vendor_perl/DR/Tarantool/MsgPack/LLClient.
```

```
unix/:/var/run/tarantool/mediator-shard-3400.control> box.space.url.index
---
- 0: &0
    unique: true
    parts:
    - type: NUM
      fieldno: 1
    id: 0
    space_id: 1
    name: primary
    type: TREE
  1: &1
    unique: false
    parts:
    - type: STR
      fieldno: 2
    id: 1
    space_id: 1
    name: secondary
    type: TREE
  primary: *0
  secondary: *1
...
```
Making only one primary index in this space solves this error.
Argument 'spaces' is not passed into DR::Tarantool::MsgPack::AsyncClient->connect method at all.

p.s.
I hope that empty spaces in this method will cause of disabling all schema 'syncing/checking' configuration routines in the future...
